kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '3'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"api:latest","namespace":"mas-test"},"fieldPath":"spec.template.spec.containers[?(@.name==\"api\")].image","pause":"true"}]
    openshift.io/generated-by: OpenShiftNewApp
  resourceVersion: '3919618499'
  name: squash
  uid: f942679f-758d-422f-af53-6684c6678c51
  creationTimestamp: '2023-03-08T14:33:39Z'
  generation: 5
  managedFields:
    - manager: oc
      operation: Update
      apiVersion: apps/v1
      time: '2023-03-08T14:33:39Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:image.openshift.io/triggers': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:openshift.io/generated-by': {}
              'f:labels':
                .: {}
                'f:deployment': {}
            'f:spec':
              'f:containers':
                'k:{"name":"api"}':
                  .: {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8001,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2023-03-08T14:35:34Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"api"}':
                  'f:envFrom': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2023-03-08T14:46:07Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"api"}':
                  'f:image': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2023-03-11T08:05:30Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
      subresource: status
  namespace: mas-test
  labels:
    app: api
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: api
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: api
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: api
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: api
          image: >-
            image-registry.openshift-image-registry.svc:5000/mas-test/api@sha256:31e74a070a14026f125e67ff3c385cefb34ca499a7580ec9007d95ec75b5a244
          ports:
            - containerPort: 8001
              protocol: TCP
          envFrom:
            - secretRef:
                name: db-secrets
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  paused: false
status:
  observedGeneration: 5
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2023-03-08T14:46:24Z'
      lastTransitionTime: '2023-03-08T14:46:07Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "api-54d8b455cb" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2023-03-11T08:05:30Z'
      lastTransitionTime: '2023-03-11T08:05:30Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
